version: '3.8'

services: 
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "3000:3000"
    networks:
      - app_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge